apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jqpe2cyt3-nodejs
  janus-idp.io/tekton: jqpe2cyt3-nodejs
  backstage.io/kubernetes-id: jqpe2cyt3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jqpe2cyt3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
